#!/usr/bin/env bash
# The per-field validators, and entrypoint.sh's spec-table interpreter that dispatches
# to them.
#
# WHY THIS IS NOT tests/render-test.sh's ground: render-test drives the whole
# entrypoint as a process, so every one of these refusals is the same exit 2. Where a
# function refuses on several arms -- validate_fingerprint_match has four, and the
# matrix reaches one of them -- the others are invisible at that granularity. Each
# case below asserts the specific message, so removing one guard fails the case that
# names it rather than being masked by a later arm that happens to refuse the same
# value.
#
# Two of these are also load-bearing in a way an exit code cannot show:
#
#   - validate_no_newlines is the only var-agnostic injection guard, and it carries a
#     deliberate carve-out for exactly ONE trailing newline (env files and command
#     substitutions routinely add one). Losing the carve-out turns ordinary deploys
#     into fatal exit 2; losing the rejection lets a config-injection value through.
#     Both directions need their own case, and neither can be asserted through
#     RELAY_HOST -- a newline is [[:space:]], so validate_no_metacharacters would
#     refuse it too and the assertion would prove nothing.
#   - validate_field_check's default arm turns a spec-table typo into a loud failure.
#     Without it, a mistyped check token silently disables that field's validation
#     while the boot log still says "input validation passed".
#
# Nothing is stubbed: these are pure shell over their arguments.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
#   SC2016 - the metacharacter cases must pass a LITERAL $ to the validator, which is
#     the character under test, so those arguments have to stay single-quoted.
# shellcheck disable=SC2015,SC2016
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The shipped shell is three files: the validators live in validate.sh, the spec-table
# interpreter in entrypoint.sh. ENTRYPOINT is reassigned before each group, and both
# paths stay overridable so a red-check can point either at a mutated /tmp copy
# without editing the repo.
EP_SH="$ENTRYPOINT"
VALIDATE_SH="${VALIDATE_SH:-$REPO_ROOT/validate.sh}"

ENTRYPOINT="$VALIDATE_SH"
# Both constants are the single source of truth for the guards below; take the real
# ones rather than a copy of their values. Explicit destinations: extract_range's
# default dest is one shared path, so two extractions would leave both variables
# naming the same file.
digits_src=$(extract_range '^readonly MAX_INT_DIGITS=' '^$' "$WORK/max_int_digits.sh") || exit 1
levels_src=$(extract_range '^readonly TLS_LEVELS=' '^$' "$WORK/tls_levels.sh") || exit 1
# Nothing is on disk for the linter to follow: the sourced paths are generated by the
# extractions above.
# shellcheck disable=SC1090
. "$digits_src"
# shellcheck disable=SC1090
. "$levels_src"

load_function sanitize_token
load_function int_too_wide
load_function validate_no_newlines
load_function validate_numeric
load_function validate_no_metacharacters
load_function validate_range
load_function validate_tls_level
load_function validate_fingerprint_digest
load_function validate_fingerprint_match
load_function validate_sasl_login
load_function validate_sasl_password

ENTRYPOINT="$EP_SH"
load_function validate_field_check

LOG="$WORK/log"

# run VALIDATOR ARGS... -- call one validator, keeping its status and its log.
run() {
  : >"$LOG"
  _rc=0
  "$@" 2>"$LOG" || _rc=$?
}

logged() {
  grep -Fq "$1" "$LOG"
}

# refuses MESSAGE LABEL -- assert the last `run` refused AND said why. The message
# check is what separates arms: several of these inputs are refused by a later guard
# too, just with different wording.
refuses() {
  [ "$_rc" -ne 0 ] && logged "$1" \
    && ok "$2" \
    || no "$2" "rc=$_rc, log: $(cat "$LOG")"
}

accepts() {
  [ "$_rc" -eq 0 ] && [ ! -s "$LOG" ] \
    && ok "$1" \
    || no "$1" "rc=$_rc, log: $(cat "$LOG")"
}

# pairs N -- a well-formed N-pair colon-separated hex digest token, so the
# fingerprint cases can vary ONE property at a time (count, or shape) instead of
# hand-writing 64 pairs per case.
pairs() {
  _p_left=$1
  _p_out=''
  while [ "$_p_left" -gt 0 ]; do
    _p_out="${_p_out:+$_p_out:}aa"
    _p_left=$((_p_left - 1))
  done
  printf '%s' "$_p_out"
}

# --- 1. validate_no_newlines: reject embedded, allow exactly one trailing ---------
NL_EMBEDDED=$(printf 'a\nb')
run validate_no_newlines RELAY_LOGIN "$NL_EMBEDDED"
refuses 'msg="env var contains embedded newlines" var=RELAY_LOGIN' \
  "an embedded newline is refused by the only var-agnostic injection guard"

# A real trailing newline has to survive the capture, which `$(...)` strips: append a
# sentinel and remove it again.
NL_TRAIL1=$(
  printf 'a\n'
  printf x
)
NL_TRAIL1=${NL_TRAIL1%x}
run validate_no_newlines RELAY_LOGIN "$NL_TRAIL1"
accepts "exactly one trailing newline is accepted, so an env-file value is not a fatal deploy failure"

NL_TRAIL2=$(
  printf 'a\n\n'
  printf x
)
NL_TRAIL2=${NL_TRAIL2%x}
run validate_no_newlines RELAY_LOGIN "$NL_TRAIL2"
refuses 'msg="env var contains embedded newlines"' \
  "two trailing newlines are still refused, so the carve-out is one newline and not all of them"

# --- 2. validate_numeric and the LONG_MAX length guard ---------------------------
run validate_numeric RELAY_PORT abc
refuses 'msg="env var must be a non-negative integer" var=RELAY_PORT' \
  "a non-numeric value is refused before any arithmetic comparison"

# 19 digits: test(1) aborts beyond LONG_MAX and validate_range's `if` swallows that
# as "in range", so width has to be refused here rather than there.
run validate_numeric MESSAGE_SIZE_LIMIT 1234567890123456789
refuses 'msg="env var numeric value too large" var=MESSAGE_SIZE_LIMIT length=19' \
  "a value too wide to compare as a shell integer is refused by length"

run validate_numeric RELAY_PORT 587
accepts "an ordinary numeric value passes"

# The boundary of the shared constant, and the one-line function definition the
# extraction harness has to emit on its own rather than sweeping to the next closer.
int_too_wide 1234567890123456789 && ! int_too_wide 123456789012345678 \
  && ok "int_too_wide is true at 19 digits and false at 18, the widest LONG_MAX-safe count" \
  || no "int_too_wide boundary" "18 digits and 19 digits are not classified differently"

# --- 3. validate_no_metacharacters ----------------------------------------------
# Not reached by render-test at all. Every character in the class gets a case,
# because the class is one pattern and a partial deletion would otherwise pass.
_meta_ok=1
_meta_bad=''
for _m in ' ' "$(printf '\t')" ';' '&' '|' '`' '$'; do
  run validate_no_metacharacters SMTP_HOSTNAME "host${_m}name"
  if [ "$_rc" -eq 0 ] || ! logged 'msg="env var contains invalid characters" var=SMTP_HOSTNAME'; then
    _meta_ok=0
    _meta_bad="${_meta_bad}[$_m]"
  fi
done
[ "$_meta_ok" -eq 1 ] \
  && ok "every shell metacharacter in the class (space, tab, ; & | backtick \$) is refused" \
  || no "metacharacter class complete" "accepted: $_meta_bad"

run validate_no_metacharacters SMTP_HOSTNAME relay.example.com
accepts "a plain FQDN passes the metacharacter check"

# --- 4. validate_range ----------------------------------------------------------
run validate_range RELAY_PORT 0 1 65535
refuses 'msg="env var out of range" var=RELAY_PORT value="0" min=1 max=65535' \
  "a value below the minimum is refused, naming the bounds"
run validate_range RELAY_PORT 65536 1 65535
refuses 'msg="env var out of range" var=RELAY_PORT value="65536" min=1 max=65535' \
  "a value above the maximum is refused"
run validate_range RELAY_PORT 1 1 65535
accepts "the minimum itself is in range (the bound is inclusive)"
run validate_range RELAY_PORT 65535 1 65535
accepts "the maximum itself is in range"

# --- 5. validate_field_check: the spec-table interpreter -------------------------
# The default arm. A typo in the table (entrypoint.sh's _spec_table) would otherwise
# skip that field's validation silently while the boot log claims validation passed.
run validate_field_check FOO bar bogus
refuses 'msg="unknown validation check" var=FOO check=bogus' \
  "an unknown spec-table check token fails loudly instead of skipping the validation"

# The range token carries its bounds inside the token, so the split has to hand MIN
# and MAX to the validator the right way round; swapped bounds would reject every
# legal port instead.
run validate_field_check RELAY_PORT 70000 range=1:65535
refuses 'value="70000" min=1 max=65535' \
  "a range=MIN:MAX token is split into the right bounds"

run validate_field_check RELAY_HOST "$NL_EMBEDDED" nl
refuses 'msg="env var contains embedded newlines" var=RELAY_HOST' \
  "the nl token dispatches to the newline validator"
run validate_field_check RELAY_PORT abc num
refuses 'msg="env var must be a non-negative integer" var=RELAY_PORT' \
  "the num token dispatches to the numeric validator"
run validate_field_check SMTP_HOSTNAME 'a$b' meta
refuses 'msg="env var contains invalid characters" var=SMTP_HOSTNAME' \
  "the meta token dispatches to the metacharacter validator"

# --- 6. validate_tls_level: the documented allowlist -----------------------------
# The eight levels are spelled out here on purpose rather than iterated from
# TLS_LEVELS: iterating the constant would assert only that it equals itself, while
# this pins the code against the documented contract in README/steering.
_lvl_bad=''
for _lvl in none may encrypt dane dane-only fingerprint verify secure; do
  run validate_tls_level "$_lvl"
  [ "$_rc" -eq 0 ] || _lvl_bad="$_lvl_bad $_lvl"
done
# shellcheck disable=SC2086
set -- $TLS_LEVELS
[ -z "$_lvl_bad" ] && [ $# -eq 8 ] \
  && ok "all eight documented TLS levels are accepted, and the allowlist holds exactly those eight" \
  || no "TLS level allowlist" "rejected:$_lvl_bad; allowlist size $#"

run validate_tls_level bogus
refuses 'msg="invalid TLS security level" var=SMTP_TLS_SECURITY_LEVEL valid="none may encrypt dane dane-only fingerprint verify secure"' \
  "an unknown TLS level is refused and the log names the whole allowlist"

# --- 7. validate_fingerprint_digest ---------------------------------------------
# render-test covers md5 end-to-end; sha1 reaches no test today, and it is the one an
# operator is most likely to try.
run validate_fingerprint_digest sha1
refuses 'msg="invalid fingerprint digest' \
  "sha1 is refused as a trust anchor (collision-weak), not just md5"
run validate_fingerprint_digest md5
refuses 'msg="invalid fingerprint digest' \
  "md5 is refused"
run validate_fingerprint_digest sha512
accepts "sha512 is accepted"
run validate_fingerprint_digest sha256
accepts "sha256 is accepted"

# --- 8. validate_fingerprint_match: four arms, one exit code --------------------
# The pair count is digest-dependent, and this is the arm the render matrix never
# reaches: a 32-pair token is correct for sha256 and can never match a sha512 peer,
# so at level=fingerprint every delivery would defer with maillog-only diagnostics.
run validate_fingerprint_match "$(pairs 32)" sha512
refuses 'want_pairs=64 digest=sha512' \
  "a 32-pair token is refused at digest=sha512 (the count is digest-dependent)"

run validate_fingerprint_match "$(pairs 32)" sha256
accepts "the same 32-pair token is accepted at digest=sha256"
run validate_fingerprint_match "$(pairs 64)" sha512
accepts "a 64-pair token is accepted at digest=sha512"

# A trailing colon with an OTHERWISE CORRECT pair count is the bait this guard
# exists for: POSIX field splitting drops the empty trailing field, so the count
# check downstream would pass it.
run validate_fingerprint_match "$(pairs 32):" sha256
refuses 'msg="fingerprint match token is not colon-separated hex pairs' \
  "a trailing colon is refused before the pair count can be fooled by the dropped empty field"

run validate_fingerprint_match "aa::$(pairs 30)" sha256
refuses 'msg="fingerprint match token is not colon-separated hex pairs' \
  "a doubled colon is refused"

run validate_fingerprint_match "zz:$(pairs 31)" sha256
refuses 'msg="fingerprint match token is not colon-separated hex pairs' \
  "a non-hex character is refused"

# A single-digit group passes the character and count checks and is caught only by
# the per-pair width check -- the fourth arm.
run validate_fingerprint_match "a:$(pairs 31)" sha256
refuses 'msg="fingerprint match token has a malformed hex pair' \
  "a one-character hex group is refused by the per-pair width check"

# Multi-token lists are the documented shape (space-separated anchors), so the loop
# has to accept every valid token rather than only the first.
run validate_fingerprint_match "$(pairs 32) $(pairs 32)" sha256
accepts "a space-separated list of valid tokens is accepted"

# --- 9. the SASL field-format checks --------------------------------------------
# sasl_passwd is parsed by splitting on the first whitespace, then the first colon,
# so these two validators are deliberately asymmetric and the asymmetry is the point.
run validate_sasl_login 'user:name'
refuses 'msg="RELAY_LOGIN must not contain whitespace or colons"' \
  "a colon in RELAY_LOGIN is refused: it would corrupt the sasl_passwd field split"
run validate_sasl_login 'user name'
refuses 'msg="RELAY_LOGIN must not contain whitespace or colons"' \
  "whitespace in RELAY_LOGIN is refused"
run validate_sasl_password 'pass word'
refuses 'msg="RELAY_PASSWORD must not contain whitespace"' \
  "whitespace in RELAY_PASSWORD is refused"
run validate_sasl_password 'pass:word'
accepts "a colon in RELAY_PASSWORD is allowed: the split takes the FIRST colon, so the rest is password"

report
