#!/usr/bin/env bash
# validate_no_open_relay() and the two per-family CIDR validators it delegates to.
#
# WHY THIS IS NOT tests/render-test.sh's ground: render-test drives the whole
# entrypoint as a process and can only observe ONE exit code. This validator refuses
# on thirteen distinct arms, so at process granularity twelve of them are
# indistinguishable from the thirteenth -- and the render matrix exercises four
# (0.0.0.0/0, a trailing dot, a leading-zero octet, an IPv6 multi-slash entry).
# Every case below asserts the SPECIFIC refusal message, which is what makes the
# arms separable: a mutant that deletes one guard has to fail the case that names it
# and only that case, even when another arm downstream still refuses the same input
# with a different message.
#
# The stakes are the app's central security property. ACCEPTED_NETWORKS becomes
# Postfix's mynetworks, so a too-broad entry is an open relay, and a malformed one
# Postfix drops at runtime with a maillog warning -- meaning the operator's LAN is
# silently excluded while validation and the healthcheck both stay green.
#
# Nothing is stubbed: these validators are pure shell over their arguments.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
# shellcheck disable=SC2015
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The shipped shell is three files and these validators live in validate.sh, so
# ENTRYPOINT is reassigned before extracting. The path stays overridable so a
# red-check can point it at a mutated /tmp copy without editing the repo.
VALIDATE_SH="${VALIDATE_SH:-$REPO_ROOT/validate.sh}"
ENTRYPOINT="$VALIDATE_SH"

# MAX_INT_DIGITS is the single source of truth for the three length guards; take the
# real constant rather than a copy of the number.
digits_src=$(extract_range '^readonly MAX_INT_DIGITS=' '^$' "$WORK/max_int_digits.sh") || exit 1
# Nothing is on disk for the linter to follow: the sourced path is generated by the
# extraction above.
# shellcheck disable=SC1090
. "$digits_src"

load_function sanitize_token
load_function int_too_wide
load_function validate_ipv6_cidr
load_function validate_ipv4_cidr
load_function warn_public_network
load_function validate_no_open_relay

LOG="$WORK/log"

# net LIST -- run the validator over a space-separated network list exactly as
# validate_relay_acceptance does, keeping the status and the rejection log.
net() {
  : >"$LOG"
  _rc=0
  validate_no_open_relay "$1" 2>"$LOG" || _rc=$?
}

logged() {
  grep -Fq "$1" "$LOG"
}

# refuses ENTRY MESSAGE LABEL -- the shape every fatal arm shares: non-zero status
# AND the arm's own message, so the case fails when ITS guard is removed even if a
# later arm still refuses the same value for a different reason.
refuses() {
  net "$1"
  [ "$_rc" -ne 0 ] && logged "$2" \
    && ok "$3" \
    || no "$3" "rc=$_rc, log: $(cat "$LOG")"
}

# --- 1. THE OPEN-RELAY GUARDS ----------------------------------------------------
# /7 is the only shape that isolates the minimum-prefix guard: 0.0.0.0/0 is caught
# by the literal arm before it (so it still refuses with that guard gone) and /8 is
# legal. Without this guard mynetworks accepts mail from far beyond the operator's
# LAN, which is the open-relay class the whole validator exists to prevent.
refuses '10.0.0.0/7' 'msg="network CIDR too broad (min /8)"' \
  "a /7 CIDR is refused as too broad even though it is otherwise well-formed"

# The IPv6 half of the literal arm. render-test covers 0.0.0.0/0; ::/0 is the same
# guard's other case and reaches no test today.
refuses '::/0' 'msg="network list contains open-relay CIDR"' \
  "the IPv6 open-relay literal ::/0 is refused"

# --- 2. the prefix must exist, be numeric, and be comparable ---------------------
# A bare address renders as a host entry Postfix reads differently from the intended
# network; the prefix is what the /8 guard above measures, so its absence has to be
# refused before that guard can mean anything.
refuses '192.168.1.5' 'msg="network entry missing CIDR prefix"' \
  "a network entry with no /prefix is refused"

refuses '10.0.0.0/x' 'msg="network entry has non-numeric prefix"' \
  "a non-numeric CIDR prefix is refused"

# test(1) aborts with "Illegal number" beyond LONG_MAX and the enclosing `if`
# swallows that as "in range", so an over-wide prefix has to be refused BY LENGTH
# before any numeric comparison. A 19-digit value still compares fine in bash, so
# without this guard the entry is refused further down as an out-of-range IPv4
# prefix -- a different message, which is what makes this case isolate the guard.
refuses '10.0.0.0/1234567890123456789' 'msg="network CIDR prefix too large"' \
  "a CIDR prefix too wide to compare as a shell integer is refused by length"

# --- 3. the address family has to be recognizable --------------------------------
refuses 'notanetwork/24' 'msg="unrecognized network format"' \
  "an entry that is neither IPv4 nor IPv6 is refused rather than passed through"

# --- 4. IPv6 arms ----------------------------------------------------------------
refuses 'fd00::/129' 'msg="IPv6 prefix out of range"' \
  "an IPv6 prefix above 128 is refused"

# Warn-only by design (rejecting it would be a config-acceptance change), but the
# warn is the operator's only signal: Postfix expands $name in main.cf values, so a
# stray character makes the entry a bad net/mask pattern that never matches.
net 'fd00::z/8'
[ "$_rc" -eq 0 ] && logged 'msg="IPv6 network entry contains characters invalid in an IPv6 address' \
  && ok "an IPv6 entry with a character invalid in an address warns without failing the boot" \
  || no "IPv6 invalid-character warn" "rc=$_rc, log: $(cat "$LOG")"

# The complement of that warn: Postfix's own mynetworks format allows an
# already-bracketed IPv6 entry, so the bracket-stripping in front of the character
# check is what keeps a legitimate value from drawing a "will never match" warning.
net '[fd00::]/8'
[ "$_rc" -eq 0 ] && [ ! -s "$LOG" ] \
  && ok "a pre-bracketed IPv6 entry ([fd00::]/8, valid Postfix syntax) passes silently" \
  || no "bracketed IPv6 entry accepted" "rc=$_rc, log: $(cat "$LOG")"

# A multi-slash IPv6 entry: Postfix would log a bad net/mask pattern and the
# network would never match, silently excluding the intended LAN. render-test
# exercises this arm too, but only as one exit 2 among thirteen; this pins the
# arm's own message so removing just this guard fails just this case.
refuses 'fd00::/8/64' 'msg="IPv6 network entry contains multiple / separators' \
  "an IPv6 entry with multiple / separators is refused"

# --- 5. IPv4 arms ----------------------------------------------------------------
refuses '192.168.1.0/33' 'msg="IPv4 prefix out of range"' \
  "an IPv4 prefix above 32 is refused"

# POSIX field splitting drops a trailing empty field, so "192.168.1.2./24" splits
# into four valid octets and would pass every per-octet check; the arm that rejects
# the trailing dot is the only thing standing between that typo and a mynetworks
# entry Postfix rejects at runtime.
refuses '192.168.1.2./24' 'msg="IPv4 address has a trailing dot"' \
  "an IPv4 address with a trailing dot is refused before field splitting hides it"

# A leading-zero octet: Postfix rejects the network entry at runtime, so the LAN it
# names is silently excluded while validation stays green.
refuses '192.168.001.0/24' 'msg="IPv4 octet has a leading zero' \
  "an IPv4 octet with a leading zero is refused"

refuses '192.168.1.2.3/24' 'msg="IPv4 address must have 4 octets"' \
  "an IPv4 address with five octets is refused"

refuses '192.168.1.a/24' 'msg="IPv4 octet not numeric"' \
  "a non-numeric IPv4 octet is refused"

refuses '192.168.1.300/24' 'msg="IPv4 octet out of range"' \
  "an IPv4 octet above 255 is refused"

# Same LONG_MAX reasoning as the prefix guard above, and the same isolation
# property: without the length guard the value is refused as out-of-range instead,
# under a different message.
refuses '1234567890123456789.0.0.0/8' 'msg="IPv4 octet too large"' \
  "an IPv4 octet too wide to compare as a shell integer is refused by length"

# --- 6. the public-address-space warn --------------------------------------------
# The /8 floor bounds the SIZE of the authorized range, never WHOSE addresses are
# in it, so a mistyped prefix (192.168.0.0/8, which Postfix masks to 192.0.0.0/8)
# satisfies every fatal arm above and still authorizes ~16M public hosts to relay.
# Warn-only by design, which makes the warn the operator's only signal.
net '192.168.0.0/8'
[ "$_rc" -eq 0 ] && logged 'msg="ACCEPTED_NETWORKS entry is not inside private address space' \
  && ok "a public-space IPv4 entry (192.168.0.0/8 masks to 192.0.0.0/8) warns without failing the boot" \
  || no "public IPv4 range warn" "rc=$_rc, log: $(cat "$LOG")"

# The IPv6 half: 2000::/16 is inside global unicast, and the first hextet must be
# read in full -- fc5::/16 is 0x0fc5, NOT inside fc00::/7, so a prefix-only match
# would wrongly stay silent on it.
net '2000::/16'
[ "$_rc" -eq 0 ] && logged 'msg="ACCEPTED_NETWORKS entry is not inside private address space' \
  && ok "a global-unicast IPv6 entry (2000::/16) warns without failing the boot" \
  || no "public IPv6 range warn" "rc=$_rc, log: $(cat "$LOG")"

# --- 7. the control: a legitimate mixed list passes silently ----------------------
# Without this, every case above would still pass against a validator that refused
# everything.
net '192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 fd00::/8'
[ "$_rc" -eq 0 ] && [ ! -s "$LOG" ] \
  && ok "the shipped RFC 1918 default plus an IPv6 ULA prefix passes with no output" \
  || no "legitimate list accepted" "rc=$_rc, log: $(cat "$LOG")"

report
