#!/usr/bin/env bash
# The startup supervision layer: run_interruptible / run_bounded /
# terminate_startup_child / timeout_log_fields, and run_postfix_checks as their real
# caller.
#
# RUN-MODE ONLY -- render mode invokes no external command at all, so
# tests/render-test.sh drives none of this. What it exists for is that the entrypoint
# is PID 1: a shell with default signal disposition IGNORES SIGTERM as PID 1, so
# every blocking startup operation is backgrounded and waited on, and a `docker stop`
# during startup is honored only if the recorded child is actually TERMed. The
# elapsed-time budget is the second half: without it a wedged spool holds startup
# open forever and Postfix never starts.
#
# timeout_log_fields is the diagnosis half. BusyBox timeout -- the only timeout in
# the runtime image -- reports an elapsed budget as 143 (its own TERM) or 137 (KILL
# after the -k grace), not coreutils' 124, so a status/arm mismatch would silently
# turn every timeout into an unexplained failure in Loki. Each status is asserted
# separately for that reason.
#
# `timeout` is the only stub: it is where the shell spawns a process, and its argv is
# the cheapest place to observe the budget the callers claim to apply.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
#   SC2034 - the variables set below are the INPUTS to entrypoint.sh code that is
#     extracted and sourced at RUNTIME, so shellcheck cannot see the reads.
# shellcheck disable=SC2015,SC2034
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The budget comes from the shipped constant rather than a copy of the number, so the
# assertions pin the WIRING (does the real budget reach the argv and the log) instead
# of restating a literal that could drift.
budget_src=$(extract_range '^readonly STARTUP_CMD_TIMEOUT=' '^$' "$WORK/startup_cmd_timeout.sh") || exit 1
# Nothing is on disk for the linter to follow: the sourced path is generated by the
# extraction above.
# shellcheck disable=SC1090
. "$budget_src"

load_function run_interruptible
load_function terminate_startup_child
load_function run_bounded
load_function timeout_log_fields
load_function run_postfix_checks

timeout() {
  printf '%s\n' "$*" >>"$ARGV"
  # run_bounded's argv is `-k 5 <budget> <cmd> [args...]`; drop the supervisor's own
  # options so the stub can answer per command.
  shift 3
  case "$*" in
    newaliases) return "$STUB_NEWALIASES" ;;
    'postfix check') return "$STUB_CHECK" ;;
    'postfix set-permissions') return "$STUB_SETPERM" ;;
  esac
  return 0
}

setup() {
  CASE=$(mktemp -d "$WORK/case.XXXXXX")
  ARGV="$CASE/argv"
  LOG="$CASE/log"
  : >"$ARGV"
  : >"$LOG"
  STUB_NEWALIASES=0
  STUB_CHECK=0
  STUB_SETPERM=0
  STARTUP_CHILD_PID=''
}

logged() {
  grep -Fq "$1" "$LOG"
}

# run_postfix_checks exits 1 on its fatal arms rather than returning, so every case
# runs it in a subshell and keeps the status.
run_checks() {
  _rc=0
  (run_postfix_checks) 2>"$LOG" || _rc=$?
}

# --- 1. the timeout statuses BusyBox actually produces ---------------------------
setup
[ "$(timeout_log_fields 143)" = " reason=timeout timeout_seconds=$STARTUP_CMD_TIMEOUT" ] \
  && ok "status 143 (BusyBox timeout's own TERM) is attributed as a timeout with the budget" \
  || no "143 attributed" "got '$(timeout_log_fields 143)'"

[ "$(timeout_log_fields 137)" = " reason=timeout timeout_seconds=$STARTUP_CMD_TIMEOUT" ] \
  && [ "$(timeout_log_fields 124)" = " reason=timeout timeout_seconds=$STARTUP_CMD_TIMEOUT" ] \
  && ok "status 137 (KILL after the -k grace) and 124 (coreutils) are attributed too" \
  || no "137/124 attributed" "137='$(timeout_log_fields 137)' 124='$(timeout_log_fields 124)'"

# A plain failure must add NOTHING: an operator who sees reason=timeout on a command
# that simply failed chases the wrong fault.
[ -z "$(timeout_log_fields 1)" ] && [ -z "$(timeout_log_fields 0)" ] \
  && [ -z "$(timeout_log_fields 2)" ] \
  && ok "an ordinary failure or success adds no timeout fields" \
  || no "non-timeout statuses stay empty" "1='$(timeout_log_fields 1)' 0='$(timeout_log_fields 0)' 2='$(timeout_log_fields 2)'"

# --- 2. run_bounded applies the budget AND the kill grace ------------------------
# The -k grace is what bounds a command that ignores the TERM; without it a wedged
# operation is TERMed and then waited on forever.
setup
run_bounded newaliases
[ "$(cat "$ARGV")" = "-k 5 $STARTUP_CMD_TIMEOUT newaliases" ] \
  && ok "run_bounded supervises the command with the shipped budget and a 5s kill grace" \
  || no "run_bounded argv" "argv: $(cat "$ARGV")"

# --- 3. run_interruptible preserves the child status and clears the handle --------
# The status matters because every caller branches on it; the cleared handle matters
# because a stale PID would make the signal handler TERM an unrelated process.
setup
child_exit_7() { exit 7; }
_rc=0
run_interruptible child_exit_7 || _rc=$?
[ "$_rc" -eq 7 ] && [ -z "$STARTUP_CHILD_PID" ] \
  && ok "run_interruptible returns the child's exit status and clears the recorded PID" \
  || no "run_interruptible status" "rc=$_rc, STARTUP_CHILD_PID='$STARTUP_CHILD_PID'"

# --- 4. terminate_startup_child TERMs the recorded child PROMPTLY ----------------
# Elapsed time is the assertion, not merely that the process is gone: a handler that
# only waits also ends with the child gone, just seconds or minutes later, which is
# exactly the docker-stop-ignored bug this function exists to prevent.
#
# Runs in a FRESH child shell: measured 3/8 spurious 10s waits when this shell's
# job table already held prior background jobs (bash job-bookkeeping under load),
# and 0/40 in a fresh process. The oracle must not inherit this file's job state.
setup
_rc=0
FNS_TERM="$WORK/terminate_startup_child.sh"
bash -c '
  set -u
  . "$1"
  sleep 10 &
  STARTUP_CHILD_PID=$!
  _child=$STARTUP_CHILD_PID
  _t0=$SECONDS
  terminate_startup_child
  _elapsed=$((SECONDS - _t0))
  [ "$_elapsed" -lt 5 ] || { echo "elapsed=${_elapsed}s" >&2; exit 1; }
  [ -z "$STARTUP_CHILD_PID" ] || { echo "pid not cleared" >&2; exit 1; }
  kill -0 "$_child" 2>/dev/null && { echo "child survived" >&2; exit 1; }
  exit 0
' _ "$FNS_TERM" 2>"$LOG"
_rc=$?
[ "$_rc" -eq 0 ] \
  && ok "terminate_startup_child TERMs and reaps the recorded child at once, then clears it" \
  || no "child terminated promptly" "$(cat "$LOG")"

# --- 5. run_postfix_checks: a missing alias database is not fatal ----------------
# newaliases is the one of the three that only affects local aliasing, which a
# relay-only MTA does not use; failing the boot over it would trade a working relay
# for a restart loop.
setup
STUB_NEWALIASES=1
run_checks
[ "$_rc" -eq 0 ] && logged 'msg="newaliases failed; continuing without alias database"' \
  && grep -Fq 'postfix set-permissions' "$ARGV" \
  && ok "a failed newaliases warns and startup continues through the remaining checks" \
  || no "newaliases is warn-only" "rc=$_rc, log: $(cat "$LOG")"

# --- 6. ... but a failed config check refuses to start ---------------------------
# Postfix would run on a config it has already rejected, so this one is fatal, and
# the later set-permissions step must not run.
setup
STUB_CHECK=1
run_checks
[ "$_rc" -ne 0 ] && logged 'msg="postfix config check failed"' \
  && ! grep -Fq 'set-permissions' "$ARGV" \
  && ok "a failed postfix config check aborts before the remaining startup steps" \
  || no "config check is fatal" "rc=$_rc, log: $(cat "$LOG")"

# --- 7. ... and so does a failed set-permissions ---------------------------------
# Wrong spool ownership means Postfix's own daemons cannot read the queue; starting
# anyway produces a relay that accepts mail and never delivers it.
setup
STUB_SETPERM=1
run_checks
[ "$_rc" -ne 0 ] && logged 'msg="postfix set-permissions failed; refusing to start"' \
  && ok "a failed postfix set-permissions refuses to start" \
  || no "set-permissions is fatal" "rc=$_rc, log: $(cat "$LOG")"

# --- 8. a timed-out check is diagnosable as a timeout at the call site ------------
# The wiring between the two halves of this file: a wedged filesystem and a rejected
# config produce the same exit path, and only the timeout fields tell them apart.
setup
STUB_CHECK=143
run_checks
[ "$_rc" -ne 0 ] \
  && logged "msg=\"postfix config check failed\" reason=timeout timeout_seconds=$STARTUP_CMD_TIMEOUT" \
  && ok "a config check killed by the budget is logged as a timeout, not a config error" \
  || no "timeout attributed at the call site" "log: $(cat "$LOG")"

report
